# Generated by Django 4.0 on 2022-01-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='Scott Kellar', max_length=200),
            preserve_default=False,
        ),
    ]
